from .crud_tag import tag
from .crud_attribute_definition import attribute_definition
from .crud_box import box
from .crud_box_template import box_template
from .crud_component import component
from .crud_inventory import inventory
from .crud_search_provider_config import search_provider_config
from .crud_sub_box import sub_box
from .crud_vlm_provider_config import vlm_provider_config
